dependencies{
	compileOnly 'com.liferay.portal:release.dxp.api'
	compileOnly 'jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.0.0'
	compileOnly 'jakarta.mail:jakarta.mail-api:2.0.1'

	cssBuilder "com.liferay:com.liferay.css.builder:3.1.4"

    compileOnly(project(":modules:common-utils"))
	testImplementation 'junit:junit:4.13.2'
}
