/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.deltares.oss.geolocation.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import nl.deltares.oss.geolocation.model.GeoLocation;
import nl.deltares.oss.geolocation.model.GeoLocationModel;

/**
 * The base model implementation for the GeoLocation service. Represents a row in the &quot;GeoLocations_GeoLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GeoLocationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GeoLocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GeoLocationImpl
 * @generated
 */
public class GeoLocationModelImpl
	extends BaseModelImpl<GeoLocation> implements GeoLocationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a geo location model instance should use the <code>GeoLocation</code> interface instead.
	 */
	public static final String TABLE_NAME = "GeoLocations_GeoLocation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"locationId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"countryId", Types.BIGINT},
		{"cityName", Types.VARCHAR}, {"latitude", Types.DOUBLE},
		{"longitude", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("locationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("countryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cityName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("latitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("longitude", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GeoLocations_GeoLocation (uuid_ VARCHAR(75) null,locationId LONG not null primary key,companyId LONG,createDate DATE null,modifiedDate DATE null,countryId LONG,cityName VARCHAR(75) null,latitude DOUBLE,longitude DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table GeoLocations_GeoLocation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY geoLocation.countryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GeoLocations_GeoLocation.countryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CITYNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COUNTRYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public GeoLocationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _locationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLocationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _locationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GeoLocation.class;
	}

	@Override
	public String getModelClassName() {
		return GeoLocation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GeoLocation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GeoLocation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GeoLocation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GeoLocation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GeoLocation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GeoLocation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GeoLocation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GeoLocation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GeoLocation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<GeoLocation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GeoLocation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GeoLocation, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GeoLocation, Object>>();
		Map<String, BiConsumer<GeoLocation, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GeoLocation, ?>>();

		attributeGetterFunctions.put("uuid", GeoLocation::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<GeoLocation, String>)GeoLocation::setUuid);
		attributeGetterFunctions.put("locationId", GeoLocation::getLocationId);
		attributeSetterBiConsumers.put(
			"locationId",
			(BiConsumer<GeoLocation, Long>)GeoLocation::setLocationId);
		attributeGetterFunctions.put("companyId", GeoLocation::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<GeoLocation, Long>)GeoLocation::setCompanyId);
		attributeGetterFunctions.put("createDate", GeoLocation::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<GeoLocation, Date>)GeoLocation::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", GeoLocation::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<GeoLocation, Date>)GeoLocation::setModifiedDate);
		attributeGetterFunctions.put("countryId", GeoLocation::getCountryId);
		attributeSetterBiConsumers.put(
			"countryId",
			(BiConsumer<GeoLocation, Long>)GeoLocation::setCountryId);
		attributeGetterFunctions.put("cityName", GeoLocation::getCityName);
		attributeSetterBiConsumers.put(
			"cityName",
			(BiConsumer<GeoLocation, String>)GeoLocation::setCityName);
		attributeGetterFunctions.put("latitude", GeoLocation::getLatitude);
		attributeSetterBiConsumers.put(
			"latitude",
			(BiConsumer<GeoLocation, Double>)GeoLocation::setLatitude);
		attributeGetterFunctions.put("longitude", GeoLocation::getLongitude);
		attributeSetterBiConsumers.put(
			"longitude",
			(BiConsumer<GeoLocation, Double>)GeoLocation::setLongitude);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getLocationId() {
		return _locationId;
	}

	@Override
	public void setLocationId(long locationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locationId = locationId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCountryId() {
		return _countryId;
	}

	@Override
	public void setCountryId(long countryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_countryId = countryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCountryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("countryId"));
	}

	@Override
	public String getCityName() {
		if (_cityName == null) {
			return "";
		}
		else {
			return _cityName;
		}
	}

	@Override
	public void setCityName(String cityName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cityName = cityName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCityName() {
		return getColumnOriginalValue("cityName");
	}

	@Override
	public double getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(double latitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_latitude = latitude;
	}

	@Override
	public double getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(double longitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_longitude = longitude;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(GeoLocation.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GeoLocation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GeoLocation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GeoLocation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GeoLocationImpl geoLocationImpl = new GeoLocationImpl();

		geoLocationImpl.setUuid(getUuid());
		geoLocationImpl.setLocationId(getLocationId());
		geoLocationImpl.setCompanyId(getCompanyId());
		geoLocationImpl.setCreateDate(getCreateDate());
		geoLocationImpl.setModifiedDate(getModifiedDate());
		geoLocationImpl.setCountryId(getCountryId());
		geoLocationImpl.setCityName(getCityName());
		geoLocationImpl.setLatitude(getLatitude());
		geoLocationImpl.setLongitude(getLongitude());

		geoLocationImpl.resetOriginalValues();

		return geoLocationImpl;
	}

	@Override
	public GeoLocation cloneWithOriginalValues() {
		GeoLocationImpl geoLocationImpl = new GeoLocationImpl();

		geoLocationImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		geoLocationImpl.setLocationId(
			this.<Long>getColumnOriginalValue("locationId"));
		geoLocationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		geoLocationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		geoLocationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		geoLocationImpl.setCountryId(
			this.<Long>getColumnOriginalValue("countryId"));
		geoLocationImpl.setCityName(
			this.<String>getColumnOriginalValue("cityName"));
		geoLocationImpl.setLatitude(
			this.<Double>getColumnOriginalValue("latitude"));
		geoLocationImpl.setLongitude(
			this.<Double>getColumnOriginalValue("longitude"));

		return geoLocationImpl;
	}

	@Override
	public int compareTo(GeoLocation geoLocation) {
		int value = 0;

		if (getCountryId() < geoLocation.getCountryId()) {
			value = -1;
		}
		else if (getCountryId() > geoLocation.getCountryId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof GeoLocation)) {
			return false;
		}

		GeoLocation geoLocation = (GeoLocation)object;

		long primaryKey = geoLocation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<GeoLocation> toCacheModel() {
		GeoLocationCacheModel geoLocationCacheModel =
			new GeoLocationCacheModel();

		geoLocationCacheModel.uuid = getUuid();

		String uuid = geoLocationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			geoLocationCacheModel.uuid = null;
		}

		geoLocationCacheModel.locationId = getLocationId();

		geoLocationCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			geoLocationCacheModel.createDate = createDate.getTime();
		}
		else {
			geoLocationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			geoLocationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			geoLocationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		geoLocationCacheModel.countryId = getCountryId();

		geoLocationCacheModel.cityName = getCityName();

		String cityName = geoLocationCacheModel.cityName;

		if ((cityName != null) && (cityName.length() == 0)) {
			geoLocationCacheModel.cityName = null;
		}

		geoLocationCacheModel.latitude = getLatitude();

		geoLocationCacheModel.longitude = getLongitude();

		return geoLocationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GeoLocation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GeoLocation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GeoLocation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((GeoLocation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GeoLocation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					GeoLocation.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _locationId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _countryId;
	private String _cityName;
	private double _latitude;
	private double _longitude;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<GeoLocation, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((GeoLocation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("locationId", _locationId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("countryId", _countryId);
		_columnOriginalValues.put("cityName", _cityName);
		_columnOriginalValues.put("latitude", _latitude);
		_columnOriginalValues.put("longitude", _longitude);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("locationId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("countryId", 32L);

		columnBitmasks.put("cityName", 64L);

		columnBitmasks.put("latitude", 128L);

		columnBitmasks.put("longitude", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private GeoLocation _escapedModel;

}