dependencies {

    implementation('com.liferay.portal:release.dxp.api')
    compileInclude 'com.maxmind.geoip2:geoip2:5.1.0'

    implementation(project(":modules:registration-service:registration-service-api"))
    implementation(project(":modules:download:download-api"))
    implementation(project(":modules:geolocation:geolocation-api"))

}