sonar.projectKey=Deltares_oss
sonar.organization=deltares
sonar.host.url=https://sonarcloud.io
sonar.sources=src/main/java
sonar.exclusions=**/build/**,**/node_modules/**,**/bundles/**,**/download/**,**/geolocation/**,**/registration-service/**
sonar.java.binaries=build/classes/java/main
sonar.java.libraries=build/libs/*.jar