/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.data.service.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RegistrationAttribute service. Represents a row in the &quot;Service_builder_RegistrationAttribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>nl.deltares.data.service.registration.model.impl.RegistrationAttributeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>nl.deltares.data.service.registration.model.impl.RegistrationAttributeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationAttribute
 * @generated
 */
@ProviderType
public interface RegistrationAttributeModel
	extends BaseModel<RegistrationAttribute> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registration attribute model instance should use the {@link RegistrationAttribute} interface instead.
	 */

	/**
	 * Returns the primary key of this registration attribute.
	 *
	 * @return the primary key of this registration attribute
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this registration attribute.
	 *
	 * @param primaryKey the primary key of this registration attribute
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the registration attribute ID of this registration attribute.
	 *
	 * @return the registration attribute ID of this registration attribute
	 */
	public long getRegistrationAttributeId();

	/**
	 * Sets the registration attribute ID of this registration attribute.
	 *
	 * @param registrationAttributeId the registration attribute ID of this registration attribute
	 */
	public void setRegistrationAttributeId(long registrationAttributeId);

	/**
	 * Returns the registration ID of this registration attribute.
	 *
	 * @return the registration ID of this registration attribute
	 */
	public long getRegistrationId();

	/**
	 * Sets the registration ID of this registration attribute.
	 *
	 * @param registrationId the registration ID of this registration attribute
	 */
	public void setRegistrationId(long registrationId);

	/**
	 * Returns the name of this registration attribute.
	 *
	 * @return the name of this registration attribute
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this registration attribute.
	 *
	 * @param name the name of this registration attribute
	 */
	public void setName(String name);

	/**
	 * Returns the value of this registration attribute.
	 *
	 * @return the value of this registration attribute
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this registration attribute.
	 *
	 * @param value the value of this registration attribute
	 */
	public void setValue(String value);

	@Override
	public RegistrationAttribute cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}