/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.data.service.registration.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RegistrationPeriod service. Represents a row in the &quot;Service_builder_RegistrationPeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>nl.deltares.data.service.registration.model.impl.RegistrationPeriodModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>nl.deltares.data.service.registration.model.impl.RegistrationPeriodImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationPeriod
 * @generated
 */
@ProviderType
public interface RegistrationPeriodModel extends BaseModel<RegistrationPeriod> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registration period model instance should use the {@link RegistrationPeriod} interface instead.
	 */

	/**
	 * Returns the primary key of this registration period.
	 *
	 * @return the primary key of this registration period
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this registration period.
	 *
	 * @param primaryKey the primary key of this registration period
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the registration period ID of this registration period.
	 *
	 * @return the registration period ID of this registration period
	 */
	public long getRegistrationPeriodId();

	/**
	 * Sets the registration period ID of this registration period.
	 *
	 * @param registrationPeriodId the registration period ID of this registration period
	 */
	public void setRegistrationPeriodId(long registrationPeriodId);

	/**
	 * Returns the registration resource ID of this registration period.
	 *
	 * @return the registration resource ID of this registration period
	 */
	public long getRegistrationResourceId();

	/**
	 * Sets the registration resource ID of this registration period.
	 *
	 * @param registrationResourceId the registration resource ID of this registration period
	 */
	public void setRegistrationResourceId(long registrationResourceId);

	/**
	 * Returns the start time of this registration period.
	 *
	 * @return the start time of this registration period
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this registration period.
	 *
	 * @param startTime the start time of this registration period
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the end time of this registration period.
	 *
	 * @return the end time of this registration period
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this registration period.
	 *
	 * @param endTime the end time of this registration period
	 */
	public void setEndTime(Date endTime);

	@Override
	public RegistrationPeriod cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}