/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.deltares.oss.download.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Download service. Represents a row in the &quot;Downloads_Download&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>nl.deltares.oss.download.model.impl.DownloadModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>nl.deltares.oss.download.model.impl.DownloadImpl</code>.
 * </p>
 *
 * @author Erik de Rooij @ Deltares
 * @see Download
 * @generated
 */
@ProviderType
public interface DownloadModel extends BaseModel<Download>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a download model instance should use the {@link Download} interface instead.
	 */

	/**
	 * Returns the primary key of this download.
	 *
	 * @return the primary key of this download
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this download.
	 *
	 * @param primaryKey the primary key of this download
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this download.
	 *
	 * @return the ID of this download
	 */
	public long getId();

	/**
	 * Sets the ID of this download.
	 *
	 * @param id the ID of this download
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this download.
	 *
	 * @return the company ID of this download
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this download.
	 *
	 * @param companyId the company ID of this download
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this download.
	 *
	 * @return the group ID of this download
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this download.
	 *
	 * @param groupId the group ID of this download
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the download ID of this download.
	 *
	 * @return the download ID of this download
	 */
	public long getDownloadId();

	/**
	 * Sets the download ID of this download.
	 *
	 * @param downloadId the download ID of this download
	 */
	public void setDownloadId(long downloadId);

	/**
	 * Returns the user ID of this download.
	 *
	 * @return the user ID of this download
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this download.
	 *
	 * @param userId the user ID of this download
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this download.
	 *
	 * @return the user uuid of this download
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this download.
	 *
	 * @param userUuid the user uuid of this download
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this download.
	 *
	 * @return the create date of this download
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this download.
	 *
	 * @param createDate the create date of this download
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this download.
	 *
	 * @return the modified date of this download
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this download.
	 *
	 * @param modifiedDate the modified date of this download
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the file path of this download.
	 *
	 * @return the file path of this download
	 */
	@AutoEscape
	public String getFilePath();

	/**
	 * Sets the file path of this download.
	 *
	 * @param filePath the file path of this download
	 */
	public void setFilePath(String filePath);

	/**
	 * Returns the expiry date of this download.
	 *
	 * @return the expiry date of this download
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this download.
	 *
	 * @param expiryDate the expiry date of this download
	 */
	public void setExpiryDate(Date expiryDate);

	/**
	 * Returns the organization of this download.
	 *
	 * @return the organization of this download
	 */
	@AutoEscape
	public String getOrganization();

	/**
	 * Sets the organization of this download.
	 *
	 * @param organization the organization of this download
	 */
	public void setOrganization(String organization);

	/**
	 * Returns the country code of this download.
	 *
	 * @return the country code of this download
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this download.
	 *
	 * @param countryCode the country code of this download
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the city of this download.
	 *
	 * @return the city of this download
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this download.
	 *
	 * @param city the city of this download
	 */
	public void setCity(String city);

	/**
	 * Returns the share ID of this download.
	 *
	 * @return the share ID of this download
	 */
	public int getShareId();

	/**
	 * Sets the share ID of this download.
	 *
	 * @param shareId the share ID of this download
	 */
	public void setShareId(int shareId);

	/**
	 * Returns the direct download url of this download.
	 *
	 * @return the direct download url of this download
	 */
	@AutoEscape
	public String getDirectDownloadUrl();

	/**
	 * Sets the direct download url of this download.
	 *
	 * @param directDownloadUrl the direct download url of this download
	 */
	public void setDirectDownloadUrl(String directDownloadUrl);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(nl.deltares.oss.download.model.Download download);

	@Override
	public int hashCode();

	@Override
	public CacheModel<nl.deltares.oss.download.model.Download> toCacheModel();

	@Override
	public nl.deltares.oss.download.model.Download toEscapedModel();

	@Override
	public nl.deltares.oss.download.model.Download toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}