/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.deltares.oss.download.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DownloadCount service. Represents a row in the &quot;Downloads_DownloadCount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>nl.deltares.oss.download.model.impl.DownloadCountModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>nl.deltares.oss.download.model.impl.DownloadCountImpl</code>.
 * </p>
 *
 * @author Erik de Rooij @ Deltares
 * @see DownloadCount
 * @generated
 */
@ProviderType
public interface DownloadCountModel
	extends BaseModel<DownloadCount>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a download count model instance should use the {@link DownloadCount} interface instead.
	 */

	/**
	 * Returns the primary key of this download count.
	 *
	 * @return the primary key of this download count
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this download count.
	 *
	 * @param primaryKey the primary key of this download count
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this download count.
	 *
	 * @return the ID of this download count
	 */
	public long getId();

	/**
	 * Sets the ID of this download count.
	 *
	 * @param id the ID of this download count
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this download count.
	 *
	 * @return the company ID of this download count
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this download count.
	 *
	 * @param companyId the company ID of this download count
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this download count.
	 *
	 * @return the group ID of this download count
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this download count.
	 *
	 * @param groupId the group ID of this download count
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the download ID of this download count.
	 *
	 * @return the download ID of this download count
	 */
	public long getDownloadId();

	/**
	 * Sets the download ID of this download count.
	 *
	 * @param downloadId the download ID of this download count
	 */
	public void setDownloadId(long downloadId);

	/**
	 * Returns the count of this download count.
	 *
	 * @return the count of this download count
	 */
	public int getCount();

	/**
	 * Sets the count of this download count.
	 *
	 * @param count the count of this download count
	 */
	public void setCount(int count);

	@Override
	public DownloadCount cloneWithOriginalValues();

}