/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.deltares.oss.download.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the DownloadCount service. Represents a row in the &quot;Downloads_DownloadCount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>nl.deltares.oss.download.model.impl.DownloadCountModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>nl.deltares.oss.download.model.impl.DownloadCountImpl</code>.
 * </p>
 *
 * @author Erik de Rooij @ Deltares
 * @see DownloadCount
 * @generated
 */
@ProviderType
public interface DownloadCountModel extends BaseModel<DownloadCount> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a download count model instance should use the {@link DownloadCount} interface instead.
	 */

	/**
	 * Returns the primary key of this download count.
	 *
	 * @return the primary key of this download count
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this download count.
	 *
	 * @param primaryKey the primary key of this download count
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the download ID of this download count.
	 *
	 * @return the download ID of this download count
	 */
	public long getDownloadId();

	/**
	 * Sets the download ID of this download count.
	 *
	 * @param downloadId the download ID of this download count
	 */
	public void setDownloadId(long downloadId);

	/**
	 * Returns the count of this download count.
	 *
	 * @return the count of this download count
	 */
	public int getCount();

	/**
	 * Sets the count of this download count.
	 *
	 * @param count the count of this download count
	 */
	public void setCount(int count);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		nl.deltares.oss.download.model.DownloadCount downloadCount);

	@Override
	public int hashCode();

	@Override
	public CacheModel<nl.deltares.oss.download.model.DownloadCount>
		toCacheModel();

	@Override
	public nl.deltares.oss.download.model.DownloadCount toEscapedModel();

	@Override
	public nl.deltares.oss.download.model.DownloadCount toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}