###
POST https://api.getgo.com/oauth/v2/token?grant_type=password&username={{username}}&password={{password}}
Authorization: Basic {{clientId}} {{clientSecret}}
Content-Type: application/x-www-form-urlencoded

###
POST https://api.getgo.com/oauth/v2/token?grant_type=refresh_token&refresh_token={{refreshToken}}
Authorization: Basic {{clientId}} {{clientSecret}}
Content-Type: application/x-www-form-urlencoded

###


