###
#POST https://use03.thegood.cloud/index.php/login/v2
#
#> {%
#client.global.set("auth_token", response.body.poll.token);
#%}


### Authorization by token, part 2. Use token to authorize.
#GET https://use03.thegood.cloud/ocs/v1.php/cloud/capabilities
# Get list of shares for a specific directory
#GET https://use03.thegood.cloud/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=oss&subfiles=true
# Get list of all shares
#GET https://use03.thegood.cloud/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json
# Get specific share info
GET https://use03.thegood.cloud/ocs/v2.php/apps/files_sharing/api/v1/shares/1935?format=json
Authorization: Basic {{username}} {{password}}
OCS-APIRequest: true

###


### Create a share using email
POST https://deltares.thegood.cloud/ocs/v2.php/apps/files_sharing/api/v1/shares?path=/download_portal/WANDA/Wanda 4.6.0&shareType=3&shareWith=e.de.rooij2@kpnplanet.nl&permissions=1&expireDate=2023-02-01
Authorization: Basic {{username}} {{password}}
OCS-APIRequest: true

###

### Create a share using group - currently disabled
POST https://use03.thegood.cloud/ocs/v2.php/apps/files_sharing/api/v1/shares?path=oss/delftfews/public&shareType=1&shareWith=group&permissions=1&expireDate=2022-02-01
Authorization: Basic {{username}} {{password}}
OCS-APIRequest: true

###

### Get a direct 8 hour share/download link
POST https://use03.thegood.cloud//ocs/v2.php/apps/dav/api/v1/direct
Content-Type: application/json
Authorization: Basic {{username}} {{password}}
OCS-APIRequest: true
#Content-Disposition: inline; filename="myfile.doc"

{
    "fileId": 5288359
}
###

### Download link for the above request
GET https://use03.thegood.cloud/remote.php/direct/FW5ENz2aJKqPc8nFa5kWgsG8pgXhhLdYhtar3vTq2BFpGtmkekHm6rb7ZGEJ
Content-Disposition: attachment; filename=myfile.doc

### Get Share
GET https://deltares.thegood.cloud/ocs/v2.php/apps/files_sharing/api/v1/shares/301
Authorization: Basic {{username}} {{password}}
OCS-APIRequest: true