###
POST http://localhost:8081/o/oauth2/token
Content-Type: application/x-www-form-urlencoded

{
  "grant_type": "client_credentials",
  "client_id": "id-a5b067cd-9cff-d9d8-ce81-f684d81af281",
  "client_secret": "secret-46751da2-353c-cd22-837d-8f5847c3d",
  "scope":"liferay-json-web-services.svnlog.write"
}

####
#GET http://localhost:8081/o/oauth2/token?grant_type=client_credentials&client_id=id-2da89a6e-acbc-d08c-5010-8a1c66536f3&client_secret=secret-3596ee8a-f2b4-461e-24f8-d23ea4383645&username=erik.derooij@deltares.nl&password=Ed3Roo(j
#
####
#GET http://localhost:8081/o/oauth2/authorize?response_type=code&client_id=id-2da89a6e-acbc-d08c-5010-8a1c66536f3&redirect_uri=http://localhost:8081/
#
#
#

