###
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}
&resource=https%3A%2F%2Fgraph.microsoft.com
&client_secret={{clientSecret}}
&grant_type=client_credentials

> {%
client.global.set("auth_token", response.body.access_token);
%}

### Authorization by token, part 2. Use token to authorize.
GET https://graph.microsoft.com/v1.0/drive
Authorization: Bearer {{auth_token}}
Accept: "application/json"