###
DELETE http://localhost:8090/o/dsd/transfer/register/{{siteId}}/{{articleId}}
Authorization: Basic {{username}} {{password}}
Accept: application/json

> {%
client.test("Delete Request", function() {
client.assert(response.status === 202, "Response status is not 200 but " + response.status);
});
%}

###
POST http://localhost:8090/o/dsd/transfer/register/{{siteId}}/{{articleId}}
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

["2020-07-17"]

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 500, "Response status is not 500 but " + response.status);
var s = response.body.message;
client.assert(s === "Validation Exception: Transfer date 2020-07-17 does not lie with valid period!", "Expected '\"Validation Exception: Transfer date 2020-07-17 does not lie with valid period!' but found : " + s)
});
%}

