dependencies {
	implementation project(":modules:geolocation:geolocation-api")

	compileOnly "com.liferay.portal:release.dxp.api"

    implementation "com.liferay:com.liferay.portal.upgrade.api:2.0.3"

}

buildService {
	apiDir = "../geolocation-api/src/main/java"
}

group = "nl.deltares.oss.geolocation"