version: '3.1'

services:

  database:
    image: mariadb:10.6.16
    container_name: oss-mariadb-74
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbliferay74:/var/lib/mysql
      - ./resources/dump-liferay.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci' ]
    networks:
      - liferay

  mariadb-keycloak:
    image: mariadb:10.4.22
    container_name: keycloak-mariadb-74
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - HOSTNAME=mariadb-keycloak
    volumes:
      - dbkeycloak74:/var/lib/mysql
      - ./resources/dump-keycloak.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci' ]
    networks:
      - liferay

  liferay:
    container_name: oss-liferay-74
    build: liferay
    ports:
      #      - 80:8080
      - 8081:8080
      - 8000:8000
      - 11311:11311
    volumes:
      - ./liferay/data:/opt/liferay/data/document_library
      - ./liferay/mount/files:/mnt/liferay/files
      - ./liferay/geoip:/opt/liferay/geoip
      - ./liferay/lmcrypt:/opt/liferay/lmcrypt
      - ${LIFERAY_BUNDLE_DIR}/deploy:/opt/liferay/deploy
      - ${LIFERAY_BUNDLE_DIR}/osgi/modules:/opt/liferay/osgi/modules
    restart: always
    networks:
      - liferay

  elasticsearch:
    container_name: oss-elastic-74
    build: elasticsearch
    environment:
      - cluster.name=oss-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ports:
      - 9200:9200
    volumes:
      - esdata74:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - liferay

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - 8080:8080
      - 8787:8787
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm", "--log-level=INFO" ]
    volumes:
      - ./keycloak/deployments:/opt/keycloak/providers
      - ./resources/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./resources/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    restart: always
    networks:
      - liferay
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Pa55w0rd
      - DEBUG=true
      - DEBUG_PORT=*:8787
      - KC_HTTP_RELATIVE_PATH=/auth
    depends_on:
      - mariadb-keycloak

volumes:
  esdata74:
    driver: local
  dbliferay74:
    driver: local
  dbkeycloak74:
    driver: local

networks:
  liferay:
