version: '3.1'

services:

  database:
    image: mariadb:10.2.25
    container_name: oss-mariadb
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbliferay:/var/lib/mysql
      - ./resources/dump-liferay.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci' ]
    networks:
      - liferay

  mariadb-keycloak:
    image: mariadb:10.2.25
    container_name: keycloak-mariadb
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - HOSTNAME=mariadb-keycloak
    volumes:
      - dbkeycloak:/var/lib/mysql
      - ./resources/dump-keycloak.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci' ]
    networks:
      - liferay

  liferay:
    container_name: oss-liferay
    build: liferay
    ports:
      #      - 80:8080
      - 8081:8080
      - 8000:8000
    volumes:
      - ./liferay/data:/opt/liferay/data/document_library
      - ./liferay/mount/files:/mnt/liferay/files
      - ./liferay/geoip:/opt/liferay/geoip
      - ${LIFERAY_BUNDLE_DIR}/deploy:/opt/liferay/deploy
      - ${LIFERAY_BUNDLE_DIR}/osgi/modules:/opt/liferay/osgi/modules
    restart: always
    networks:
      - liferay

  elasticsearch:
    container_name: oss-elastic
    build: elasticsearch
    environment:
      - cluster.name=oss-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - liferay

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    container_name: keycloak
    #    build: server
    ports:
      - 8080:8080
      - 8443:8443
      - 8787:8787
#      - 9990:9990
    volumes:
      - ./keycloak/deployments:/opt/jboss/keycloak/standalone/deployments
      - ./resources:/opt/jboss/keycloak/resources
    restart: always
    networks:
      - liferay
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb-keycloak
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - DEBUG=true
      - DEBUG_PORT=*:8787
      - HOSTNAME=keycloak
    #    depends_on:
    #      - mariadb
    #    These commands are required to allow remote debugging with docker
    command: [ "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.port=12345",
               "-Dcom.sun.management.jmxremote.local.only=false", "-Dcom.sun.management.jmxremote.authenticate=false",
               "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.rmi.port=12345",
               "-Djava.rmi.server.hostname=$HOSTNAME",
               "-Dkeycloak.import=/opt/jboss/keycloak/resources/realm-lportal.json",
               "-Dkeycloak.profile.feature.upload_scripts=enabled" ]

  openldap:
    image: bitnami/openldap:2
    container_name: openldap
    #      build: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      #        - LDAP_USERS=rooij_e
      #        - LDAP_PASSWORDS=password
      - LDAP_ROOT=dc=oss,dc=deltares,dc=nl
      - LDAP_BindDN=cn=admin,dc=oss,dc=deltares,dc=nl
      - LDAP_BindPW=admin
      - LDAP_USER_DC=people
      - LDAP_GROUP=groups
#      - LDAP_ADD_SCHEMAS=yes
#      - LDAP_EXTRA_SCHEMAS=cosine, inetorgperson, nis,ppolicy
    #        - LDAP_CUSTOM_LDIF_DIR=/opt/bitnami/openldap/etc/ldifs/
    volumes:
      - openldap:/bitnami/openldap
    networks:
      - liferay


volumes:
  esdata:
    driver: local
  dbliferay:
    driver: local
  dbkeycloak:
    driver: local
  openldap:
    driver: local

networks:
  liferay:

  ## admin account
  # admin / pass
  #
  # Default user password: F$5tR32WFGt12_k98
