/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.worth.deltares.oss.subversion.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import nl.worth.deltares.oss.subversion.model.RepositoryFolderPermission;
import nl.worth.deltares.oss.subversion.model.RepositoryFolderPermissionModel;
import nl.worth.deltares.oss.subversion.model.RepositoryFolderPermissionSoap;

/**
 * The base model implementation for the RepositoryFolderPermission service. Represents a row in the &quot;Subversion_RepositoryFolderPermission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RepositoryFolderPermissionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RepositoryFolderPermissionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RepositoryFolderPermissionImpl
 * @generated
 */
@JSON(strict = true)
public class RepositoryFolderPermissionModelImpl
	extends BaseModelImpl<RepositoryFolderPermission>
	implements RepositoryFolderPermissionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a repository folder permission model instance should use the <code>RepositoryFolderPermission</code> interface instead.
	 */
	public static final String TABLE_NAME =
		"Subversion_RepositoryFolderPermission";

	public static final Object[][] TABLE_COLUMNS = {
		{"permissionId", Types.BIGINT}, {"folderId", Types.BIGINT},
		{"permission", Types.VARCHAR}, {"recurse", Types.BOOLEAN},
		{"entityType", Types.VARCHAR}, {"entityId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("permissionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("folderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("permission", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("recurse", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("entityType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Subversion_RepositoryFolderPermission (permissionId LONG not null primary key,folderId LONG,permission VARCHAR(75) null,recurse BOOLEAN,entityType VARCHAR(75) null,entityId LONG,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table Subversion_RepositoryFolderPermission";

	public static final String ORDER_BY_JPQL =
		" ORDER BY repositoryFolderPermission.permissionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Subversion_RepositoryFolderPermission.permissionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FOLDERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PERMISSIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static RepositoryFolderPermission toModel(
		RepositoryFolderPermissionSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		RepositoryFolderPermission model = new RepositoryFolderPermissionImpl();

		model.setPermissionId(soapModel.getPermissionId());
		model.setFolderId(soapModel.getFolderId());
		model.setPermission(soapModel.getPermission());
		model.setRecurse(soapModel.isRecurse());
		model.setEntityType(soapModel.getEntityType());
		model.setEntityId(soapModel.getEntityId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<RepositoryFolderPermission> toModels(
		RepositoryFolderPermissionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RepositoryFolderPermission> models =
			new ArrayList<RepositoryFolderPermission>(soapModels.length);

		for (RepositoryFolderPermissionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public RepositoryFolderPermissionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _permissionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPermissionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _permissionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RepositoryFolderPermission.class;
	}

	@Override
	public String getModelClassName() {
		return RepositoryFolderPermission.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RepositoryFolderPermission, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RepositoryFolderPermission, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RepositoryFolderPermission, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(RepositoryFolderPermission)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RepositoryFolderPermission, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RepositoryFolderPermission, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RepositoryFolderPermission)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RepositoryFolderPermission, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RepositoryFolderPermission, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RepositoryFolderPermission>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RepositoryFolderPermission.class.getClassLoader(),
			RepositoryFolderPermission.class, ModelWrapper.class);

		try {
			Constructor<RepositoryFolderPermission> constructor =
				(Constructor<RepositoryFolderPermission>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<RepositoryFolderPermission, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<RepositoryFolderPermission, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<RepositoryFolderPermission, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<RepositoryFolderPermission, Object>>();
		Map<String, BiConsumer<RepositoryFolderPermission, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<RepositoryFolderPermission, ?>>();

		attributeGetterFunctions.put(
			"permissionId", RepositoryFolderPermission::getPermissionId);
		attributeSetterBiConsumers.put(
			"permissionId",
			(BiConsumer<RepositoryFolderPermission, Long>)
				RepositoryFolderPermission::setPermissionId);
		attributeGetterFunctions.put(
			"folderId", RepositoryFolderPermission::getFolderId);
		attributeSetterBiConsumers.put(
			"folderId",
			(BiConsumer<RepositoryFolderPermission, Long>)
				RepositoryFolderPermission::setFolderId);
		attributeGetterFunctions.put(
			"permission", RepositoryFolderPermission::getPermission);
		attributeSetterBiConsumers.put(
			"permission",
			(BiConsumer<RepositoryFolderPermission, String>)
				RepositoryFolderPermission::setPermission);
		attributeGetterFunctions.put(
			"recurse", RepositoryFolderPermission::getRecurse);
		attributeSetterBiConsumers.put(
			"recurse",
			(BiConsumer<RepositoryFolderPermission, Boolean>)
				RepositoryFolderPermission::setRecurse);
		attributeGetterFunctions.put(
			"entityType", RepositoryFolderPermission::getEntityType);
		attributeSetterBiConsumers.put(
			"entityType",
			(BiConsumer<RepositoryFolderPermission, String>)
				RepositoryFolderPermission::setEntityType);
		attributeGetterFunctions.put(
			"entityId", RepositoryFolderPermission::getEntityId);
		attributeSetterBiConsumers.put(
			"entityId",
			(BiConsumer<RepositoryFolderPermission, Long>)
				RepositoryFolderPermission::setEntityId);
		attributeGetterFunctions.put(
			"createDate", RepositoryFolderPermission::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<RepositoryFolderPermission, Date>)
				RepositoryFolderPermission::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", RepositoryFolderPermission::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<RepositoryFolderPermission, Date>)
				RepositoryFolderPermission::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getPermissionId() {
		return _permissionId;
	}

	@Override
	public void setPermissionId(long permissionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_permissionId = permissionId;
	}

	@JSON
	@Override
	public long getFolderId() {
		return _folderId;
	}

	@Override
	public void setFolderId(long folderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_folderId = folderId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFolderId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("folderId"));
	}

	@JSON
	@Override
	public String getPermission() {
		if (_permission == null) {
			return "";
		}
		else {
			return _permission;
		}
	}

	@Override
	public void setPermission(String permission) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_permission = permission;
	}

	@JSON
	@Override
	public boolean getRecurse() {
		return _recurse;
	}

	@JSON
	@Override
	public boolean isRecurse() {
		return _recurse;
	}

	@Override
	public void setRecurse(boolean recurse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recurse = recurse;
	}

	@JSON
	@Override
	public String getEntityType() {
		if (_entityType == null) {
			return "";
		}
		else {
			return _entityType;
		}
	}

	@Override
	public void setEntityType(String entityType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityType = entityType;
	}

	@JSON
	@Override
	public long getEntityId() {
		return _entityId;
	}

	@Override
	public void setEntityId(long entityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityId = entityId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RepositoryFolderPermission.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RepositoryFolderPermission toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RepositoryFolderPermission>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RepositoryFolderPermissionImpl repositoryFolderPermissionImpl =
			new RepositoryFolderPermissionImpl();

		repositoryFolderPermissionImpl.setPermissionId(getPermissionId());
		repositoryFolderPermissionImpl.setFolderId(getFolderId());
		repositoryFolderPermissionImpl.setPermission(getPermission());
		repositoryFolderPermissionImpl.setRecurse(isRecurse());
		repositoryFolderPermissionImpl.setEntityType(getEntityType());
		repositoryFolderPermissionImpl.setEntityId(getEntityId());
		repositoryFolderPermissionImpl.setCreateDate(getCreateDate());
		repositoryFolderPermissionImpl.setModifiedDate(getModifiedDate());

		repositoryFolderPermissionImpl.resetOriginalValues();

		return repositoryFolderPermissionImpl;
	}

	@Override
	public RepositoryFolderPermission cloneWithOriginalValues() {
		RepositoryFolderPermissionImpl repositoryFolderPermissionImpl =
			new RepositoryFolderPermissionImpl();

		repositoryFolderPermissionImpl.setPermissionId(
			this.<Long>getColumnOriginalValue("permissionId"));
		repositoryFolderPermissionImpl.setFolderId(
			this.<Long>getColumnOriginalValue("folderId"));
		repositoryFolderPermissionImpl.setPermission(
			this.<String>getColumnOriginalValue("permission"));
		repositoryFolderPermissionImpl.setRecurse(
			this.<Boolean>getColumnOriginalValue("recurse"));
		repositoryFolderPermissionImpl.setEntityType(
			this.<String>getColumnOriginalValue("entityType"));
		repositoryFolderPermissionImpl.setEntityId(
			this.<Long>getColumnOriginalValue("entityId"));
		repositoryFolderPermissionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		repositoryFolderPermissionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return repositoryFolderPermissionImpl;
	}

	@Override
	public int compareTo(
		RepositoryFolderPermission repositoryFolderPermission) {

		long primaryKey = repositoryFolderPermission.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RepositoryFolderPermission)) {
			return false;
		}

		RepositoryFolderPermission repositoryFolderPermission =
			(RepositoryFolderPermission)object;

		long primaryKey = repositoryFolderPermission.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RepositoryFolderPermission> toCacheModel() {
		RepositoryFolderPermissionCacheModel
			repositoryFolderPermissionCacheModel =
				new RepositoryFolderPermissionCacheModel();

		repositoryFolderPermissionCacheModel.permissionId = getPermissionId();

		repositoryFolderPermissionCacheModel.folderId = getFolderId();

		repositoryFolderPermissionCacheModel.permission = getPermission();

		String permission = repositoryFolderPermissionCacheModel.permission;

		if ((permission != null) && (permission.length() == 0)) {
			repositoryFolderPermissionCacheModel.permission = null;
		}

		repositoryFolderPermissionCacheModel.recurse = isRecurse();

		repositoryFolderPermissionCacheModel.entityType = getEntityType();

		String entityType = repositoryFolderPermissionCacheModel.entityType;

		if ((entityType != null) && (entityType.length() == 0)) {
			repositoryFolderPermissionCacheModel.entityType = null;
		}

		repositoryFolderPermissionCacheModel.entityId = getEntityId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			repositoryFolderPermissionCacheModel.createDate =
				createDate.getTime();
		}
		else {
			repositoryFolderPermissionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			repositoryFolderPermissionCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			repositoryFolderPermissionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return repositoryFolderPermissionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RepositoryFolderPermission, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RepositoryFolderPermission, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RepositoryFolderPermission, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RepositoryFolderPermission)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RepositoryFolderPermission, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RepositoryFolderPermission, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RepositoryFolderPermission, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(RepositoryFolderPermission)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, RepositoryFolderPermission>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _permissionId;
	private long _folderId;
	private String _permission;
	private boolean _recurse;
	private String _entityType;
	private long _entityId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<RepositoryFolderPermission, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RepositoryFolderPermission)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("permissionId", _permissionId);
		_columnOriginalValues.put("folderId", _folderId);
		_columnOriginalValues.put("permission", _permission);
		_columnOriginalValues.put("recurse", _recurse);
		_columnOriginalValues.put("entityType", _entityType);
		_columnOriginalValues.put("entityId", _entityId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("permissionId", 1L);

		columnBitmasks.put("folderId", 2L);

		columnBitmasks.put("permission", 4L);

		columnBitmasks.put("recurse", 8L);

		columnBitmasks.put("entityType", 16L);

		columnBitmasks.put("entityId", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RepositoryFolderPermission _escapedModel;

}