/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.worth.deltares.subversion.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.worth.deltares.subversion.model.RepositoryLog;
import com.worth.deltares.subversion.model.RepositoryLogModel;
import com.worth.deltares.subversion.model.RepositoryLogSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RepositoryLog service. Represents a row in the &quot;deltares_RepositoryLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link RepositoryLogModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RepositoryLogImpl}.
 * </p>
 *
 * @author Pier-Angelo Gaetani @ Worth Systems
 * @see RepositoryLogImpl
 * @see RepositoryLog
 * @see RepositoryLogModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RepositoryLogModelImpl extends BaseModelImpl<RepositoryLog>
	implements RepositoryLogModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a repository log model instance should use the {@link RepositoryLog} interface instead.
	 */
	public static final String TABLE_NAME = "deltares_RepositoryLog";
	public static final Object[][] TABLE_COLUMNS = {
			{ "logId", Types.BIGINT },
			{ "ipAddress", Types.VARCHAR },
			{ "screenName", Types.VARCHAR },
			{ "action", Types.VARCHAR },
			{ "createDate", Types.BIGINT },
			{ "repository", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("logId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("screenName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("action", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("repository", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table deltares_RepositoryLog (logId LONG not null primary key,ipAddress VARCHAR(75) null,screenName VARCHAR(75) null,action VARCHAR(75) null,createDate LONG,repository VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table deltares_RepositoryLog";
	public static final String ORDER_BY_JPQL = " ORDER BY repositoryLog.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY deltares_RepositoryLog.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.worth.deltares.subversion.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.worth.deltares.subversion.model.RepositoryLog"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.worth.deltares.subversion.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.worth.deltares.subversion.model.RepositoryLog"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RepositoryLog toModel(RepositoryLogSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RepositoryLog model = new RepositoryLogImpl();

		model.setLogId(soapModel.getLogId());
		model.setIpAddress(soapModel.getIpAddress());
		model.setScreenName(soapModel.getScreenName());
		model.setAction(soapModel.getAction());
		model.setCreateDate(soapModel.getCreateDate());
		model.setRepository(soapModel.getRepository());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RepositoryLog> toModels(RepositoryLogSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RepositoryLog> models = new ArrayList<RepositoryLog>(soapModels.length);

		for (RepositoryLogSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.worth.deltares.subversion.service.util.ServiceProps.get(
				"lock.expiration.time.com.worth.deltares.subversion.model.RepositoryLog"));

	public RepositoryLogModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _logId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLogId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _logId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RepositoryLog.class;
	}

	@Override
	public String getModelClassName() {
		return RepositoryLog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("logId", getLogId());
		attributes.put("ipAddress", getIpAddress());
		attributes.put("screenName", getScreenName());
		attributes.put("action", getAction());
		attributes.put("createDate", getCreateDate());
		attributes.put("repository", getRepository());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long logId = (Long)attributes.get("logId");

		if (logId != null) {
			setLogId(logId);
		}

		String ipAddress = (String)attributes.get("ipAddress");

		if (ipAddress != null) {
			setIpAddress(ipAddress);
		}

		String screenName = (String)attributes.get("screenName");

		if (screenName != null) {
			setScreenName(screenName);
		}

		String action = (String)attributes.get("action");

		if (action != null) {
			setAction(action);
		}

		Long createDate = (Long)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		String repository = (String)attributes.get("repository");

		if (repository != null) {
			setRepository(repository);
		}
	}

	@JSON
	@Override
	public long getLogId() {
		return _logId;
	}

	@Override
	public void setLogId(long logId) {
		_logId = logId;
	}

	@JSON
	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return "";
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		_ipAddress = ipAddress;
	}

	@JSON
	@Override
	public String getScreenName() {
		if (_screenName == null) {
			return "";
		}
		else {
			return _screenName;
		}
	}

	@Override
	public void setScreenName(String screenName) {
		_screenName = screenName;
	}

	@JSON
	@Override
	public String getAction() {
		if (_action == null) {
			return "";
		}
		else {
			return _action;
		}
	}

	@Override
	public void setAction(String action) {
		_action = action;
	}

	@JSON
	@Override
	public long getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(long createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public String getRepository() {
		if (_repository == null) {
			return "";
		}
		else {
			return _repository;
		}
	}

	@Override
	public void setRepository(String repository) {
		_repository = repository;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RepositoryLog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RepositoryLog toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RepositoryLog)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RepositoryLogImpl repositoryLogImpl = new RepositoryLogImpl();

		repositoryLogImpl.setLogId(getLogId());
		repositoryLogImpl.setIpAddress(getIpAddress());
		repositoryLogImpl.setScreenName(getScreenName());
		repositoryLogImpl.setAction(getAction());
		repositoryLogImpl.setCreateDate(getCreateDate());
		repositoryLogImpl.setRepository(getRepository());

		repositoryLogImpl.resetOriginalValues();

		return repositoryLogImpl;
	}

	@Override
	public int compareTo(RepositoryLog repositoryLog) {
		int value = 0;

		if (getCreateDate() < repositoryLog.getCreateDate()) {
			value = -1;
		}
		else if (getCreateDate() > repositoryLog.getCreateDate()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RepositoryLog)) {
			return false;
		}

		RepositoryLog repositoryLog = (RepositoryLog)obj;

		long primaryKey = repositoryLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RepositoryLog> toCacheModel() {
		RepositoryLogCacheModel repositoryLogCacheModel = new RepositoryLogCacheModel();

		repositoryLogCacheModel.logId = getLogId();

		repositoryLogCacheModel.ipAddress = getIpAddress();

		String ipAddress = repositoryLogCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			repositoryLogCacheModel.ipAddress = null;
		}

		repositoryLogCacheModel.screenName = getScreenName();

		String screenName = repositoryLogCacheModel.screenName;

		if ((screenName != null) && (screenName.length() == 0)) {
			repositoryLogCacheModel.screenName = null;
		}

		repositoryLogCacheModel.action = getAction();

		String action = repositoryLogCacheModel.action;

		if ((action != null) && (action.length() == 0)) {
			repositoryLogCacheModel.action = null;
		}

		repositoryLogCacheModel.createDate = getCreateDate();

		repositoryLogCacheModel.repository = getRepository();

		String repository = repositoryLogCacheModel.repository;

		if ((repository != null) && (repository.length() == 0)) {
			repositoryLogCacheModel.repository = null;
		}

		return repositoryLogCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{logId=");
		sb.append(getLogId());
		sb.append(", ipAddress=");
		sb.append(getIpAddress());
		sb.append(", screenName=");
		sb.append(getScreenName());
		sb.append(", action=");
		sb.append(getAction());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", repository=");
		sb.append(getRepository());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.worth.deltares.subversion.model.RepositoryLog");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>logId</column-name><column-value><![CDATA[");
		sb.append(getLogId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ipAddress</column-name><column-value><![CDATA[");
		sb.append(getIpAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>screenName</column-name><column-value><![CDATA[");
		sb.append(getScreenName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>action</column-name><column-value><![CDATA[");
		sb.append(getAction());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>repository</column-name><column-value><![CDATA[");
		sb.append(getRepository());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = RepositoryLog.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			RepositoryLog.class
		};
	private long _logId;
	private String _ipAddress;
	private String _screenName;
	private String _action;
	private long _createDate;
	private String _repository;
	private RepositoryLog _escapedModel;
}