/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.dsd.registration.model.impl;

import nl.deltares.dsd.registration.model.Registration;
import nl.deltares.dsd.registration.service.RegistrationLocalServiceUtil;

/**
 * The extended model base implementation for the Registration service. Represents a row in the &quot;Registrations_Registration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationImpl}.
 * </p>
 *
 * @author Erik de Rooij @ Deltares
 * @see RegistrationImpl
 * @see Registration
 * @generated
 */
public abstract class RegistrationBaseImpl
	extends RegistrationModelImpl implements Registration {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registration model instance should use the <code>Registration</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RegistrationLocalServiceUtil.addRegistration(this);
		}
		else {
			RegistrationLocalServiceUtil.updateRegistration(this);
		}
	}

}