/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.data.service.registration.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import nl.deltares.data.service.registration.model.RegistrationPeriod;
import nl.deltares.data.service.registration.model.RegistrationPeriodModel;

/**
 * The base model implementation for the RegistrationPeriod service. Represents a row in the &quot;Service_builder_RegistrationPeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RegistrationPeriodModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationPeriodImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationPeriodImpl
 * @generated
 */
public class RegistrationPeriodModelImpl
	extends BaseModelImpl<RegistrationPeriod>
	implements RegistrationPeriodModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registration period model instance should use the <code>RegistrationPeriod</code> interface instead.
	 */
	public static final String TABLE_NAME =
		"Service_builder_RegistrationPeriod";

	public static final Object[][] TABLE_COLUMNS = {
		{"registrationPeriodId", Types.BIGINT},
		{"registrationResourceId", Types.BIGINT},
		{"startTime", Types.TIMESTAMP}, {"endTime", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("registrationPeriodId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("registrationResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endTime", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Service_builder_RegistrationPeriod (registrationPeriodId LONG not null primary key,registrationResourceId LONG,startTime DATE null,endTime DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table Service_builder_RegistrationPeriod";

	public static final String ORDER_BY_JPQL =
		" ORDER BY registrationPeriod.registrationPeriodId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Service_builder_RegistrationPeriod.registrationPeriodId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REGISTRATIONRESOURCEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REGISTRATIONPERIODID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RegistrationPeriodModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _registrationPeriodId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRegistrationPeriodId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _registrationPeriodId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RegistrationPeriod.class;
	}

	@Override
	public String getModelClassName() {
		return RegistrationPeriod.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RegistrationPeriod, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RegistrationPeriod, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegistrationPeriod, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RegistrationPeriod)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RegistrationPeriod, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RegistrationPeriod, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RegistrationPeriod)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RegistrationPeriod, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RegistrationPeriod, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<RegistrationPeriod, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<RegistrationPeriod, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<RegistrationPeriod, Object>>();

			attributeGetterFunctions.put(
				"registrationPeriodId",
				RegistrationPeriod::getRegistrationPeriodId);
			attributeGetterFunctions.put(
				"registrationResourceId",
				RegistrationPeriod::getRegistrationResourceId);
			attributeGetterFunctions.put(
				"startTime", RegistrationPeriod::getStartTime);
			attributeGetterFunctions.put(
				"endTime", RegistrationPeriod::getEndTime);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<RegistrationPeriod, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<RegistrationPeriod, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<RegistrationPeriod, ?>>();

			attributeSetterBiConsumers.put(
				"registrationPeriodId",
				(BiConsumer<RegistrationPeriod, Long>)
					RegistrationPeriod::setRegistrationPeriodId);
			attributeSetterBiConsumers.put(
				"registrationResourceId",
				(BiConsumer<RegistrationPeriod, Long>)
					RegistrationPeriod::setRegistrationResourceId);
			attributeSetterBiConsumers.put(
				"startTime",
				(BiConsumer<RegistrationPeriod, Date>)
					RegistrationPeriod::setStartTime);
			attributeSetterBiConsumers.put(
				"endTime",
				(BiConsumer<RegistrationPeriod, Date>)
					RegistrationPeriod::setEndTime);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getRegistrationPeriodId() {
		return _registrationPeriodId;
	}

	@Override
	public void setRegistrationPeriodId(long registrationPeriodId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registrationPeriodId = registrationPeriodId;
	}

	@Override
	public long getRegistrationResourceId() {
		return _registrationResourceId;
	}

	@Override
	public void setRegistrationResourceId(long registrationResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registrationResourceId = registrationResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRegistrationResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("registrationResourceId"));
	}

	@Override
	public Date getStartTime() {
		return _startTime;
	}

	@Override
	public void setStartTime(Date startTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startTime = startTime;
	}

	@Override
	public Date getEndTime() {
		return _endTime;
	}

	@Override
	public void setEndTime(Date endTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endTime = endTime;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RegistrationPeriod.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RegistrationPeriod toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RegistrationPeriod>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RegistrationPeriodImpl registrationPeriodImpl =
			new RegistrationPeriodImpl();

		registrationPeriodImpl.setRegistrationPeriodId(
			getRegistrationPeriodId());
		registrationPeriodImpl.setRegistrationResourceId(
			getRegistrationResourceId());
		registrationPeriodImpl.setStartTime(getStartTime());
		registrationPeriodImpl.setEndTime(getEndTime());

		registrationPeriodImpl.resetOriginalValues();

		return registrationPeriodImpl;
	}

	@Override
	public RegistrationPeriod cloneWithOriginalValues() {
		RegistrationPeriodImpl registrationPeriodImpl =
			new RegistrationPeriodImpl();

		registrationPeriodImpl.setRegistrationPeriodId(
			this.<Long>getColumnOriginalValue("registrationPeriodId"));
		registrationPeriodImpl.setRegistrationResourceId(
			this.<Long>getColumnOriginalValue("registrationResourceId"));
		registrationPeriodImpl.setStartTime(
			this.<Date>getColumnOriginalValue("startTime"));
		registrationPeriodImpl.setEndTime(
			this.<Date>getColumnOriginalValue("endTime"));

		return registrationPeriodImpl;
	}

	@Override
	public int compareTo(RegistrationPeriod registrationPeriod) {
		long primaryKey = registrationPeriod.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RegistrationPeriod)) {
			return false;
		}

		RegistrationPeriod registrationPeriod = (RegistrationPeriod)object;

		long primaryKey = registrationPeriod.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RegistrationPeriod> toCacheModel() {
		RegistrationPeriodCacheModel registrationPeriodCacheModel =
			new RegistrationPeriodCacheModel();

		registrationPeriodCacheModel.registrationPeriodId =
			getRegistrationPeriodId();

		registrationPeriodCacheModel.registrationResourceId =
			getRegistrationResourceId();

		Date startTime = getStartTime();

		if (startTime != null) {
			registrationPeriodCacheModel.startTime = startTime.getTime();
		}
		else {
			registrationPeriodCacheModel.startTime = Long.MIN_VALUE;
		}

		Date endTime = getEndTime();

		if (endTime != null) {
			registrationPeriodCacheModel.endTime = endTime.getTime();
		}
		else {
			registrationPeriodCacheModel.endTime = Long.MIN_VALUE;
		}

		return registrationPeriodCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RegistrationPeriod, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RegistrationPeriod, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegistrationPeriod, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RegistrationPeriod)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RegistrationPeriod>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RegistrationPeriod.class, ModelWrapper.class);

	}

	private long _registrationPeriodId;
	private long _registrationResourceId;
	private Date _startTime;
	private Date _endTime;

	public <T> T getColumnValue(String columnName) {
		Function<RegistrationPeriod, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RegistrationPeriod)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"registrationPeriodId", _registrationPeriodId);
		_columnOriginalValues.put(
			"registrationResourceId", _registrationResourceId);
		_columnOriginalValues.put("startTime", _startTime);
		_columnOriginalValues.put("endTime", _endTime);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("registrationPeriodId", 1L);

		columnBitmasks.put("registrationResourceId", 2L);

		columnBitmasks.put("startTime", 4L);

		columnBitmasks.put("endTime", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RegistrationPeriod _escapedModel;

}