/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.data.service.registration.model.impl;

import nl.deltares.data.service.registration.model.RegistrationPeriod;
import nl.deltares.data.service.registration.service.RegistrationPeriodLocalServiceUtil;

/**
 * The extended model base implementation for the RegistrationPeriod service. Represents a row in the &quot;Service_builder_RegistrationPeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationPeriodImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationPeriodImpl
 * @see RegistrationPeriod
 * @generated
 */
public abstract class RegistrationPeriodBaseImpl
	extends RegistrationPeriodModelImpl implements RegistrationPeriod {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registration period model instance should use the <code>RegistrationPeriod</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RegistrationPeriodLocalServiceUtil.addRegistrationPeriod(this);
		}
		else {
			RegistrationPeriodLocalServiceUtil.updateRegistrationPeriod(this);
		}
	}

}