/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.data.service.registration.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import nl.deltares.data.service.registration.model.RegistrationResource;
import nl.deltares.data.service.registration.model.RegistrationResourceModel;

/**
 * The base model implementation for the RegistrationResource service. Represents a row in the &quot;Service_builder_RegistrationResource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RegistrationResourceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationResourceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationResourceImpl
 * @generated
 */
public class RegistrationResourceModelImpl
	extends BaseModelImpl<RegistrationResource>
	implements RegistrationResourceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registration resource model instance should use the <code>RegistrationResource</code> interface instead.
	 */
	public static final String TABLE_NAME =
		"Service_builder_RegistrationResource";

	public static final Object[][] TABLE_COLUMNS = {
		{"registrationResourceId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"eventResourceId", Types.BIGINT},
		{"parentResourceId", Types.BIGINT}, {"resourceName", Types.VARCHAR},
		{"eventResourceName", Types.VARCHAR}, {"eventArticleId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("registrationResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("eventResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resourceName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventResourceName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventArticleId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Service_builder_RegistrationResource (registrationResourceId LONG not null primary key,companyId LONG,groupId LONG,eventResourceId LONG,parentResourceId LONG,resourceName VARCHAR(255) null,eventResourceName VARCHAR(255) null,eventArticleId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table Service_builder_RegistrationResource";

	public static final String ORDER_BY_JPQL =
		" ORDER BY registrationResource.registrationResourceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Service_builder_RegistrationResource.registrationResourceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EVENTARTICLEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EVENTRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTRESOURCEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REGISTRATIONRESOURCEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RegistrationResourceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _registrationResourceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRegistrationResourceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _registrationResourceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RegistrationResource.class;
	}

	@Override
	public String getModelClassName() {
		return RegistrationResource.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RegistrationResource, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RegistrationResource, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegistrationResource, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RegistrationResource)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RegistrationResource, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RegistrationResource, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RegistrationResource)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RegistrationResource, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RegistrationResource, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<RegistrationResource, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<RegistrationResource, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<RegistrationResource, Object>>();

			attributeGetterFunctions.put(
				"registrationResourceId",
				RegistrationResource::getRegistrationResourceId);
			attributeGetterFunctions.put(
				"companyId", RegistrationResource::getCompanyId);
			attributeGetterFunctions.put(
				"groupId", RegistrationResource::getGroupId);
			attributeGetterFunctions.put(
				"eventResourceId", RegistrationResource::getEventResourceId);
			attributeGetterFunctions.put(
				"parentResourceId", RegistrationResource::getParentResourceId);
			attributeGetterFunctions.put(
				"resourceName", RegistrationResource::getResourceName);
			attributeGetterFunctions.put(
				"eventResourceName",
				RegistrationResource::getEventResourceName);
			attributeGetterFunctions.put(
				"eventArticleId", RegistrationResource::getEventArticleId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<RegistrationResource, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<RegistrationResource, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<RegistrationResource, ?>>();

			attributeSetterBiConsumers.put(
				"registrationResourceId",
				(BiConsumer<RegistrationResource, Long>)
					RegistrationResource::setRegistrationResourceId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<RegistrationResource, Long>)
					RegistrationResource::setCompanyId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<RegistrationResource, Long>)
					RegistrationResource::setGroupId);
			attributeSetterBiConsumers.put(
				"eventResourceId",
				(BiConsumer<RegistrationResource, Long>)
					RegistrationResource::setEventResourceId);
			attributeSetterBiConsumers.put(
				"parentResourceId",
				(BiConsumer<RegistrationResource, Long>)
					RegistrationResource::setParentResourceId);
			attributeSetterBiConsumers.put(
				"resourceName",
				(BiConsumer<RegistrationResource, String>)
					RegistrationResource::setResourceName);
			attributeSetterBiConsumers.put(
				"eventResourceName",
				(BiConsumer<RegistrationResource, String>)
					RegistrationResource::setEventResourceName);
			attributeSetterBiConsumers.put(
				"eventArticleId",
				(BiConsumer<RegistrationResource, Long>)
					RegistrationResource::setEventArticleId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getRegistrationResourceId() {
		return _registrationResourceId;
	}

	@Override
	public void setRegistrationResourceId(long registrationResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registrationResourceId = registrationResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRegistrationResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("registrationResourceId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getEventResourceId() {
		return _eventResourceId;
	}

	@Override
	public void setEventResourceId(long eventResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventResourceId = eventResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEventResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("eventResourceId"));
	}

	@Override
	public long getParentResourceId() {
		return _parentResourceId;
	}

	@Override
	public void setParentResourceId(long parentResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentResourceId = parentResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentResourceId"));
	}

	@Override
	public String getResourceName() {
		if (_resourceName == null) {
			return "";
		}
		else {
			return _resourceName;
		}
	}

	@Override
	public void setResourceName(String resourceName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resourceName = resourceName;
	}

	@Override
	public String getEventResourceName() {
		if (_eventResourceName == null) {
			return "";
		}
		else {
			return _eventResourceName;
		}
	}

	@Override
	public void setEventResourceName(String eventResourceName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventResourceName = eventResourceName;
	}

	@Override
	public long getEventArticleId() {
		return _eventArticleId;
	}

	@Override
	public void setEventArticleId(long eventArticleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventArticleId = eventArticleId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEventArticleId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("eventArticleId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), RegistrationResource.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RegistrationResource toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RegistrationResource>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RegistrationResourceImpl registrationResourceImpl =
			new RegistrationResourceImpl();

		registrationResourceImpl.setRegistrationResourceId(
			getRegistrationResourceId());
		registrationResourceImpl.setCompanyId(getCompanyId());
		registrationResourceImpl.setGroupId(getGroupId());
		registrationResourceImpl.setEventResourceId(getEventResourceId());
		registrationResourceImpl.setParentResourceId(getParentResourceId());
		registrationResourceImpl.setResourceName(getResourceName());
		registrationResourceImpl.setEventResourceName(getEventResourceName());
		registrationResourceImpl.setEventArticleId(getEventArticleId());

		registrationResourceImpl.resetOriginalValues();

		return registrationResourceImpl;
	}

	@Override
	public RegistrationResource cloneWithOriginalValues() {
		RegistrationResourceImpl registrationResourceImpl =
			new RegistrationResourceImpl();

		registrationResourceImpl.setRegistrationResourceId(
			this.<Long>getColumnOriginalValue("registrationResourceId"));
		registrationResourceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		registrationResourceImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		registrationResourceImpl.setEventResourceId(
			this.<Long>getColumnOriginalValue("eventResourceId"));
		registrationResourceImpl.setParentResourceId(
			this.<Long>getColumnOriginalValue("parentResourceId"));
		registrationResourceImpl.setResourceName(
			this.<String>getColumnOriginalValue("resourceName"));
		registrationResourceImpl.setEventResourceName(
			this.<String>getColumnOriginalValue("eventResourceName"));
		registrationResourceImpl.setEventArticleId(
			this.<Long>getColumnOriginalValue("eventArticleId"));

		return registrationResourceImpl;
	}

	@Override
	public int compareTo(RegistrationResource registrationResource) {
		long primaryKey = registrationResource.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RegistrationResource)) {
			return false;
		}

		RegistrationResource registrationResource =
			(RegistrationResource)object;

		long primaryKey = registrationResource.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RegistrationResource> toCacheModel() {
		RegistrationResourceCacheModel registrationResourceCacheModel =
			new RegistrationResourceCacheModel();

		registrationResourceCacheModel.registrationResourceId =
			getRegistrationResourceId();

		registrationResourceCacheModel.companyId = getCompanyId();

		registrationResourceCacheModel.groupId = getGroupId();

		registrationResourceCacheModel.eventResourceId = getEventResourceId();

		registrationResourceCacheModel.parentResourceId = getParentResourceId();

		registrationResourceCacheModel.resourceName = getResourceName();

		String resourceName = registrationResourceCacheModel.resourceName;

		if ((resourceName != null) && (resourceName.length() == 0)) {
			registrationResourceCacheModel.resourceName = null;
		}

		registrationResourceCacheModel.eventResourceName =
			getEventResourceName();

		String eventResourceName =
			registrationResourceCacheModel.eventResourceName;

		if ((eventResourceName != null) && (eventResourceName.length() == 0)) {
			registrationResourceCacheModel.eventResourceName = null;
		}

		registrationResourceCacheModel.eventArticleId = getEventArticleId();

		return registrationResourceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RegistrationResource, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RegistrationResource, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegistrationResource, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RegistrationResource)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RegistrationResource>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RegistrationResource.class, ModelWrapper.class);

	}

	private long _registrationResourceId;
	private long _companyId;
	private long _groupId;
	private long _eventResourceId;
	private long _parentResourceId;
	private String _resourceName;
	private String _eventResourceName;
	private long _eventArticleId;

	public <T> T getColumnValue(String columnName) {
		Function<RegistrationResource, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RegistrationResource)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"registrationResourceId", _registrationResourceId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("eventResourceId", _eventResourceId);
		_columnOriginalValues.put("parentResourceId", _parentResourceId);
		_columnOriginalValues.put("resourceName", _resourceName);
		_columnOriginalValues.put("eventResourceName", _eventResourceName);
		_columnOriginalValues.put("eventArticleId", _eventArticleId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("registrationResourceId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("eventResourceId", 8L);

		columnBitmasks.put("parentResourceId", 16L);

		columnBitmasks.put("resourceName", 32L);

		columnBitmasks.put("eventResourceName", 64L);

		columnBitmasks.put("eventArticleId", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RegistrationResource _escapedModel;

}