/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.data.service.registration.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import nl.deltares.data.service.registration.model.RegistrationAttribute;
import nl.deltares.data.service.registration.model.RegistrationAttributeModel;

/**
 * The base model implementation for the RegistrationAttribute service. Represents a row in the &quot;Service_builder_RegistrationAttribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RegistrationAttributeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationAttributeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationAttributeImpl
 * @generated
 */
public class RegistrationAttributeModelImpl
	extends BaseModelImpl<RegistrationAttribute>
	implements RegistrationAttributeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registration attribute model instance should use the <code>RegistrationAttribute</code> interface instead.
	 */
	public static final String TABLE_NAME =
		"Service_builder_RegistrationAttribute";

	public static final Object[][] TABLE_COLUMNS = {
		{"registrationAttributeId", Types.BIGINT},
		{"registrationId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("registrationAttributeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("registrationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Service_builder_RegistrationAttribute (registrationAttributeId LONG not null primary key,registrationId LONG,name VARCHAR(75) null,value STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table Service_builder_RegistrationAttribute";

	public static final String ORDER_BY_JPQL =
		" ORDER BY registrationAttribute.registrationAttributeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Service_builder_RegistrationAttribute.registrationAttributeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REGISTRATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REGISTRATIONATTRIBUTEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RegistrationAttributeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _registrationAttributeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRegistrationAttributeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _registrationAttributeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RegistrationAttribute.class;
	}

	@Override
	public String getModelClassName() {
		return RegistrationAttribute.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RegistrationAttribute, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RegistrationAttribute, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegistrationAttribute, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RegistrationAttribute)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RegistrationAttribute, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RegistrationAttribute, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RegistrationAttribute)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RegistrationAttribute, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RegistrationAttribute, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<RegistrationAttribute, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<RegistrationAttribute, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<RegistrationAttribute, Object>>();

			attributeGetterFunctions.put(
				"registrationAttributeId",
				RegistrationAttribute::getRegistrationAttributeId);
			attributeGetterFunctions.put(
				"registrationId", RegistrationAttribute::getRegistrationId);
			attributeGetterFunctions.put(
				"name", RegistrationAttribute::getName);
			attributeGetterFunctions.put(
				"value", RegistrationAttribute::getValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<RegistrationAttribute, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<RegistrationAttribute, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<RegistrationAttribute, ?>>();

			attributeSetterBiConsumers.put(
				"registrationAttributeId",
				(BiConsumer<RegistrationAttribute, Long>)
					RegistrationAttribute::setRegistrationAttributeId);
			attributeSetterBiConsumers.put(
				"registrationId",
				(BiConsumer<RegistrationAttribute, Long>)
					RegistrationAttribute::setRegistrationId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<RegistrationAttribute, String>)
					RegistrationAttribute::setName);
			attributeSetterBiConsumers.put(
				"value",
				(BiConsumer<RegistrationAttribute, String>)
					RegistrationAttribute::setValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getRegistrationAttributeId() {
		return _registrationAttributeId;
	}

	@Override
	public void setRegistrationAttributeId(long registrationAttributeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registrationAttributeId = registrationAttributeId;
	}

	@Override
	public long getRegistrationId() {
		return _registrationId;
	}

	@Override
	public void setRegistrationId(long registrationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_registrationId = registrationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRegistrationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("registrationId"));
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RegistrationAttribute.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RegistrationAttribute toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RegistrationAttribute>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RegistrationAttributeImpl registrationAttributeImpl =
			new RegistrationAttributeImpl();

		registrationAttributeImpl.setRegistrationAttributeId(
			getRegistrationAttributeId());
		registrationAttributeImpl.setRegistrationId(getRegistrationId());
		registrationAttributeImpl.setName(getName());
		registrationAttributeImpl.setValue(getValue());

		registrationAttributeImpl.resetOriginalValues();

		return registrationAttributeImpl;
	}

	@Override
	public RegistrationAttribute cloneWithOriginalValues() {
		RegistrationAttributeImpl registrationAttributeImpl =
			new RegistrationAttributeImpl();

		registrationAttributeImpl.setRegistrationAttributeId(
			this.<Long>getColumnOriginalValue("registrationAttributeId"));
		registrationAttributeImpl.setRegistrationId(
			this.<Long>getColumnOriginalValue("registrationId"));
		registrationAttributeImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		registrationAttributeImpl.setValue(
			this.<String>getColumnOriginalValue("value"));

		return registrationAttributeImpl;
	}

	@Override
	public int compareTo(RegistrationAttribute registrationAttribute) {
		long primaryKey = registrationAttribute.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RegistrationAttribute)) {
			return false;
		}

		RegistrationAttribute registrationAttribute =
			(RegistrationAttribute)object;

		long primaryKey = registrationAttribute.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RegistrationAttribute> toCacheModel() {
		RegistrationAttributeCacheModel registrationAttributeCacheModel =
			new RegistrationAttributeCacheModel();

		registrationAttributeCacheModel.registrationAttributeId =
			getRegistrationAttributeId();

		registrationAttributeCacheModel.registrationId = getRegistrationId();

		registrationAttributeCacheModel.name = getName();

		String name = registrationAttributeCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			registrationAttributeCacheModel.name = null;
		}

		registrationAttributeCacheModel.value = getValue();

		String value = registrationAttributeCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			registrationAttributeCacheModel.value = null;
		}

		return registrationAttributeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RegistrationAttribute, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RegistrationAttribute, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegistrationAttribute, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RegistrationAttribute)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RegistrationAttribute>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RegistrationAttribute.class, ModelWrapper.class);

	}

	private long _registrationAttributeId;
	private long _registrationId;
	private String _name;
	private String _value;

	public <T> T getColumnValue(String columnName) {
		Function<RegistrationAttribute, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RegistrationAttribute)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"registrationAttributeId", _registrationAttributeId);
		_columnOriginalValues.put("registrationId", _registrationId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("value", _value);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("registrationAttributeId", 1L);

		columnBitmasks.put("registrationId", 2L);

		columnBitmasks.put("name", 4L);

		columnBitmasks.put("value", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RegistrationAttribute _escapedModel;

}