/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.data.service.registration.model.impl;

import nl.deltares.data.service.registration.model.RegistrationAttribute;
import nl.deltares.data.service.registration.service.RegistrationAttributeLocalServiceUtil;

/**
 * The extended model base implementation for the RegistrationAttribute service. Represents a row in the &quot;Service_builder_RegistrationAttribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationAttributeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationAttributeImpl
 * @see RegistrationAttribute
 * @generated
 */
public abstract class RegistrationAttributeBaseImpl
	extends RegistrationAttributeModelImpl implements RegistrationAttribute {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registration attribute model instance should use the <code>RegistrationAttribute</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RegistrationAttributeLocalServiceUtil.addRegistrationAttribute(
				this);
		}
		else {
			RegistrationAttributeLocalServiceUtil.updateRegistrationAttribute(
				this);
		}
	}

}