/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.data.service.registration.model.impl;

import nl.deltares.data.service.registration.model.RegistrationResource;
import nl.deltares.data.service.registration.service.RegistrationResourceLocalServiceUtil;

/**
 * The extended model base implementation for the RegistrationResource service. Represents a row in the &quot;Service_builder_RegistrationResource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationResourceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationResourceImpl
 * @see RegistrationResource
 * @generated
 */
public abstract class RegistrationResourceBaseImpl
	extends RegistrationResourceModelImpl implements RegistrationResource {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a registration resource model instance should use the <code>RegistrationResource</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RegistrationResourceLocalServiceUtil.addRegistrationResource(this);
		}
		else {
			RegistrationResourceLocalServiceUtil.updateRegistrationResource(
				this);
		}
	}

}