/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package nl.deltares.oss.download.model.impl;

import nl.deltares.oss.download.model.DownloadCount;
import nl.deltares.oss.download.service.DownloadCountLocalServiceUtil;

/**
 * The extended model base implementation for the DownloadCount service. Represents a row in the &quot;Downloads_DownloadCount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DownloadCountImpl}.
 * </p>
 *
 * @author Erik de Rooij @ Deltares
 * @see DownloadCountImpl
 * @see DownloadCount
 * @generated
 */
public abstract class DownloadCountBaseImpl
	extends DownloadCountModelImpl implements DownloadCount {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a download count model instance should use the <code>DownloadCount</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DownloadCountLocalServiceUtil.addDownloadCount(this);
		}
		else {
			DownloadCountLocalServiceUtil.updateDownloadCount(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:2112082655