/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package nl.deltares.oss.download.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import nl.deltares.oss.download.model.DownloadCount;
import nl.deltares.oss.download.model.DownloadCountModel;

/**
 * The base model implementation for the DownloadCount service. Represents a row in the &quot;Downloads_DownloadCount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>DownloadCountModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DownloadCountImpl}.
 * </p>
 *
 * @author Erik de Rooij @ Deltares
 * @see DownloadCountImpl
 * @generated
 */
@ProviderType
public class DownloadCountModelImpl
	extends BaseModelImpl<DownloadCount> implements DownloadCountModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a download count model instance should use the <code>DownloadCount</code> interface instead.
	 */
	public static final String TABLE_NAME = "Downloads_DownloadCount";

	public static final Object[][] TABLE_COLUMNS = {
		{"downloadId", Types.BIGINT}, {"count", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("downloadId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("count", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Downloads_DownloadCount (downloadId LONG not null primary key,count INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table Downloads_DownloadCount";

	public static final String ORDER_BY_JPQL =
		" ORDER BY downloadCount.count DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Downloads_DownloadCount.count DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		nl.deltares.oss.download.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.nl.deltares.oss.download.model.DownloadCount"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		nl.deltares.oss.download.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.nl.deltares.oss.download.model.DownloadCount"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		nl.deltares.oss.download.service.util.ServiceProps.get(
			"lock.expiration.time.nl.deltares.oss.download.model.DownloadCount"));

	public DownloadCountModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _downloadId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDownloadId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _downloadId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DownloadCount.class;
	}

	@Override
	public String getModelClassName() {
		return DownloadCount.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DownloadCount, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DownloadCount, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DownloadCount, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DownloadCount)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DownloadCount, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DownloadCount, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DownloadCount)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DownloadCount, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DownloadCount, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DownloadCount>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DownloadCount.class.getClassLoader(), DownloadCount.class,
			ModelWrapper.class);

		try {
			Constructor<DownloadCount> constructor =
				(Constructor<DownloadCount>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<DownloadCount, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DownloadCount, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DownloadCount, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DownloadCount, Object>>();
		Map<String, BiConsumer<DownloadCount, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DownloadCount, ?>>();

		attributeGetterFunctions.put(
			"downloadId",
			new Function<DownloadCount, Object>() {

				@Override
				public Object apply(DownloadCount downloadCount) {
					return downloadCount.getDownloadId();
				}

			});
		attributeSetterBiConsumers.put(
			"downloadId",
			new BiConsumer<DownloadCount, Object>() {

				@Override
				public void accept(
					DownloadCount downloadCount, Object downloadId) {

					downloadCount.setDownloadId((Long)downloadId);
				}

			});
		attributeGetterFunctions.put(
			"count",
			new Function<DownloadCount, Object>() {

				@Override
				public Object apply(DownloadCount downloadCount) {
					return downloadCount.getCount();
				}

			});
		attributeSetterBiConsumers.put(
			"count",
			new BiConsumer<DownloadCount, Object>() {

				@Override
				public void accept(DownloadCount downloadCount, Object count) {
					downloadCount.setCount((Integer)count);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getDownloadId() {
		return _downloadId;
	}

	@Override
	public void setDownloadId(long downloadId) {
		_downloadId = downloadId;
	}

	@Override
	public int getCount() {
		return _count;
	}

	@Override
	public void setCount(int count) {
		_count = count;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DownloadCount.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DownloadCount toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DownloadCount>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DownloadCountImpl downloadCountImpl = new DownloadCountImpl();

		downloadCountImpl.setDownloadId(getDownloadId());
		downloadCountImpl.setCount(getCount());

		downloadCountImpl.resetOriginalValues();

		return downloadCountImpl;
	}

	@Override
	public int compareTo(DownloadCount downloadCount) {
		int value = 0;

		if (getCount() < downloadCount.getCount()) {
			value = -1;
		}
		else if (getCount() > downloadCount.getCount()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DownloadCount)) {
			return false;
		}

		DownloadCount downloadCount = (DownloadCount)obj;

		long primaryKey = downloadCount.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DownloadCount> toCacheModel() {
		DownloadCountCacheModel downloadCountCacheModel =
			new DownloadCountCacheModel();

		downloadCountCacheModel.downloadId = getDownloadId();

		downloadCountCacheModel.count = getCount();

		return downloadCountCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DownloadCount, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DownloadCount, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DownloadCount, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((DownloadCount)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DownloadCount, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DownloadCount, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DownloadCount, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DownloadCount)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DownloadCount>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _downloadId;
	private int _count;
	private DownloadCount _escapedModel;

}