name: Sync Repository to GitLab

on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Sync to GitLab
        uses: keninkujovic/gitlab-sync@2.1.0
        with:
          gitlab_url: https://open-git.deltares.nl/mydeltares/oss.git
          username: ${{ secrets.GITLAB_USERNAME }}
          gitlab_pat: ${{ secrets.GITLAB_PAT }}